backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "projects"
    label: "Projects"
    extension: "json"
    editor:
      preview: false
    label_singular: "Project" # Used in the UI, ie: "New Post"
    folder: "content/project"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Cover", name: "cover", widget: "image", required: false}
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown"}

